(function(m){var window=this;var jF=function(a,b){if("FORM"==a.tagName)for(var c=a.elements,d=0;a=c[d];d++)jF(a,b);else!0==b&&a.blur(),a.disabled=b};var kF=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};var lF=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);(0,m.Dd)(a)}};
var mF=function(a,b){this.j=a;this.D=b;this.b=null;this.k=(0,m.N)("page");this.b=(0,m.S)((0,m.N)("premium-yva-close"),"click",(0,m.r)(this.xh,this));m.Re.getInstance().get("HIDDEN_MASTHEAD_ID")==this.j||(0,m.J)(this.k,"masthead-ad-expanded")};var nF=function(a){var b=m.Re.getInstance();b.set("HIDDEN_MASTHEAD_ID",a);b.save()};
var oF=function(a,b){this.M="session_token="+a;(this.b=window.document.location.protocol+"//"+window.document.location.hostname)&&"/"!=this.b.charAt(this.b.length-1)&&(this.b+="/");this.k=b;this.D=null;this.H=[];this.F=[];this.J={}};var pF=function(){return(0,m.O)("feed-item-checkbox",qF)};var rF=function(a){sF(a.currentTarget.checked)};var tF=function(a){a="false"!=(0,m.C)(a.currentTarget,"enabled");(0,m.wo)(uF,a);sF(a)};var sF=function(a){(0,m.z)(pF(),function(b){(0,m.wo)(b,a)});vF()};var wF=function(){vF()};
var vF=function(){var a=[],b=!0,c=pF();(0,m.z)(c,function(c){c.checked&&(a.push(c.value),b=!1)});(0,m.D)(xF,"video-ids",a.join(","));jF(xF,b);jF(yF,b);jF(zF,b);AF&&jF(AF,0==c.length)};
var BF=function(){var a=(0,m.C)(xF,"video-ids"),b={};switch(CF){case "history":b.action_remove_history_entries=1;break;case "watch_later":b.action_remove_watch_later_entries=1;break;case "favorites":b.action_remove_favorites_entries=1;break;default:throw Error("Unsupported feed name: "+CF);}(0,m.X)("/feed_change_ajax",{method:"POST",Q:b,R:{session_token:(0,m.G)("feed_change_ajax"),video_ids:a},N:DF,onError:EF})};
var DF=function(){var a=0;(0,m.z)(pF(),function(b){b.checked&&((0,m.Dd)((0,m.Yd)(b,"li")),a+=1)});if(FF){var b=(0,window.parseInt)(FF.innerHTML.replace(/[^\d\.\ ]/g,""),10);FF.innerHTML=b-a}vF();(0,m.wo)(uF,!1);(0,m.Aq)(qF)};var EF=function(){m.R.hide(GF);m.R.show(HF)};var IF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_pause_history:1},R:{session_token:(0,m.G)("feed_change_ajax")},N:JF,onError:EF})};var JF=function(){KF((0,m.F)("HISTORY_FEED_PAUSED"))};
var LF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_resume_history:1},R:{session_token:(0,m.G)("feed_change_ajax")},N:MF,onError:EF})};var MF=function(){KF((0,m.F)("HISTORY_FEED_RESUMED"))};var KF=function(a){NF(a);m.R.toggle((0,m.N)("watch-history-pause-container"),(0,m.N)("watch-history-resume-container"))};var NF=function(a){(0,m.P)("yt-alert-content",GF).innerHTML=a;m.R.show(GF);m.R.hide(HF)};
var OF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_clear_history:1},R:{session_token:(0,m.G)("feed_change_ajax")},N:PF,onError:EF})};var PF=function(){NF((0,m.F)("HISTORY_FEED_CLEARED"));var a=pF();0!=a.length&&((0,m.Yd)(a[0],"ul").innerHTML="",vF())};var QF=function(a){RF(a.currentTarget)};
var RF=function(a){a=(0,m.Q)(a,"feed-container");var b=(0,m.Q)(a,"individual-feed"),c=(0,m.C)(b,"feed-name")||null,b=(0,m.C)(b,"feed-type")||null,d=(0,m.C)(a,"filter-type")||null;(0,m.C)(a,"view-type");var e=(0,m.C)(a,"paging")||null;SF(a,c,b,d,e)};
var SF=function(a,b,c,d,e){c=TF(b,c,d,e);b=c.url;c=c.Q;var g=(0,m.P)("feed-load-more-container",a);(0,m.J)(g,"loading");(0,m.X)(b,{Q:c,format:"JSON",N:function(b,c){var d=(0,m.bg)(c.feed_html);if(d){var e=(0,m.P)("last",a);e&&(0,m.K)(e,"last");(0,m.Ad)(d,g);(0,m.Aq)(d);m.Xw.getInstance().Jb();(0,m.K)(g,"loading");c.paging?(0,m.D)(a,"paging",c.paging):m.R.hide(g);m.R.hide(UF)}else(0,m.K)(g,"loading")},onError:function(){(0,m.K)(g,"loading");m.R.show(UF)}})};
var VF=function(a){a=a.getServiceInfo();for(var b in a){var c=(0,m.N)(b+"-connected");if(c){var d=a[b],e=(0,m.N)(b+"-not-connected"),g=(0,m.N)(b+"-display-name"),h=d.is_connected;m.R.ab(c,h);m.R.ab(e,!h);(0,m.Qd)(g,d.connected_as||"")}}};var WF=function(){m.R.hide("mep-container");(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_music_promo:"1"},R:{session_token:(0,m.G)("engagement_wizard_ajax")}})};var XF=function(a){return(0,m.Q)(a.currentTarget,"mep-artist-lockup")};
var YF=function(a){var b=XF(a),c=(0,m.P)("mep-artist-thumb",b);a=(0,m.C)(c,"artist-id");(0,m.J)(b,"removed");(0,m.K)(b,"subbed");(0,m.K)(c,"yt-uix-tooltip");c=ZF.shift();(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_item_mep1:"1"},R:{session_token:(0,m.G)("engagement_wizard_ajax"),dismissed_channel:a,next_channel:c},N:function(a,c){(0,m.nv)(b,{duration:0.5,da:function(){b.innerHTML=c.html_content;lF(b);m.R.hide(b);(0,m.mv)(b,0,1,{duration:0.5})}})}})};
var $F=function(a){var b=(0,m.N)("mep-container"),c=(0,m.N)("mep-player-container"),d=XF(a);a=(0,m.C)((0,m.P)("mep-artist-thumb",XF(a)),"artist-id");if(!(0,m.L)(b,"working")&&!(0,m.L)(d,"removed")){(0,m.J)(b,"open");(0,m.J)(b,"working");(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_select_artist:"1"},R:{channel_id:a,setting_type:"SUBSCRIPTIONS",session_token:(0,m.G)("engagement_wizard_ajax")},N:function(a,e){m.R.show(c);(0,m.K)(b,"working");(0,m.J)(d,"subbed");c.innerHTML=e.html_content;
(0,m.Aq)(c)}});var e=(0,m.C)(d,"sessionlink");(0,m.A)("subscription-subscribe",a,null,null,e)}};var aG=function(a){var b=(0,m.N)("mep-container");if(null!=b)for(var b=(0,m.O)("yt-uix-subscription-button",b),c=0;c<b.length;c++)if((0,m.C)(b[c],"channel-external-id")==a){a=(0,m.Q)(b[c],"music-promo-item");bG(a);(0,m.J)(a,"subscribed");break}};
var cG=function(a){var b=(0,m.Q)(a.currentTarget,"music-promo-item");a=(0,m.C)(b,"external-id");var c=(0,m.L)(b,"last")?1:0,d=ZF.shift();(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_item_mep2:"1"},R:{session_token:(0,m.G)("engagement_wizard_ajax"),dismissed_channel:a,next_channel:d,is_last_item:c,column_name:(0,m.v)("MEP_COLUMN_NAME")},da:function(a,c){(0,m.nv)(b,{duration:0.5,da:function(){var a=c.html_content;m.R.hide(b);a&&(b.innerHTML=a,lF(b),(0,m.mv)(b,0,1,{duration:0.5}));
if(0==ZF.length)for(var a=(0,m.O)("mep2-dismiss-button"),d=0;d<a.length;d++)m.R.setVisible(a[d],!1)}})}})};var dG=function(a){a=(0,m.Q)(a.currentTarget,"music-promo-item");var b=(0,m.L)(a,"collapsed"),c=(0,m.L)(a,"subscribed");b&&c&&bG(a)};var bG=function(a){if(!(0,m.L)(a,"expanded")){var b=(0,m.N)("mep-container");null!=b&&((b=(0,m.P)("expanded",b))&&(0,m.Zc)(b,"expanded","collapsed"),(0,m.Zc)(a,"collapsed","expanded"))}};
var eG=function(a){kF(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.$c)(a,"collapsed","expanded");m.ep.getInstance().ce()};var fG=function(a){kF(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.$c)(a,"expanded","collapsed");m.ep.getInstance().ce()};
var gG=function(a){kF(a);var b=(0,m.Q)(a.currentTarget,"context-data-item");a=(0,m.Q)(a.currentTarget,"feed-item-container");b=(0,m.C)(b,"context-item-id");a.parentNode.innerHTML='<iframe type="text/html" width="640" height="390" src="http://www.youtube.com/embed/__VID__?autoplay=1" frameborder="0"/>'.replace("__VID__",b)};
var TF=function(a,b,c,d){var e="",g={};"personal"==b?(e="/feed_ajax?action_load_personal_feed=1",g={feed_name:a}):"social"==b?(e="/feed_ajax?action_load_social_feed=1",g={feed_name:a}):"system"==b?(e="/feed_ajax?action_load_system_feed=1",g={feed_name:a}):"main"==b?e="/feed_ajax?action_load_main_feed=1":"user"==b?(e="/feed_ajax?action_load_user_feed=1",g={user_id:a}):"collection"==b&&(e="/feed_ajax?action_load_collection_feed=1",g={collection_id:a});c&&(g.filter_type=c);d&&(g.paging=d);(0,m.v)("FEED_DEBUG")&&
(g.debug=(0,m.v)("FEED_DEBUG"));return{url:e,Q:g}};var hG=function(){var a=(0,m.v)("PYV_IFRAME_CONTENT"),b=(0,m.N)((0,m.v)("PYV_IFRAME_ID"));b&&(b=b.contentDocument||b.contentWindow.document,b.open(),b.write("<!DOCTYPE html><html><head></head><body>"+a+"</body></html>"),m.I||b.close())};var iG=function(){var a=(0,m.N)("destination-moments-promo");if(a){var b=(0,m.C)(a,"column-name")||"";jG=(0,m.V)(a,"click",(0,m.Cb)(kG,b),"destination-moments-promo-close")}};
var kG=function(a){var b=m.Re.getInstance();(0,m.Xe)(0,m.Qf.Mq,!0);b.save();m.R.hide((0,m.N)("destination-moments-promo"));(new m.iw(a)).write("write_reject")};var lG=function(){(0,m.U)(mG);(0,m.Da)(nG);(0,m.z)(oG,function(a){(0,m.x)(a)})};var pG=function(a){a.preventDefault();a=(0,m.Q)(a.currentTarget,"branded-page-related-channels-item");qG(a,!0)};var rG=function(a){(0,m.nv)(a,{duration:0.3,da:function(){(0,m.Dd)(a)}})};
var sG=function(a){var b=(0,m.O)("branded-page-related-channels-item"),c=(0,m.Bb)(b,function(b){return(0,m.C)(b,"external-id")==a});c&&oG.push((0,m.w)(function(){qG(c,!1)},2E3))};
var qG=function(a,b){var c=window.document.getElementById("channels_you_may_know"),c=c&&(0,m.Pd)(c,a),d=!!(0,m.P)("branded-page-related-channels-featured-badge",a),e=(0,m.C)(a,"external-id"),g=(0,m.Yd)(a,"ul"),g=(0,m.O)("branded-page-related-channels-item",g),g=(0,m.rb)(g,function(a){return(0,m.C)(a,"external-id")}),h={};d&&(h.featured=1);c&&(h.channels_you_may_know=1);(0,m.X)("/guide_ajax?action_reload_channel=1",{method:"POST",Q:h,R:{session_token:(0,m.G)("guide_ajax"),dismissed_id:e,shown_ids:g.join(),
dismiss_old_channel:b},N:function(b,c){var d=c.new_suggested_html;d?(d=(0,m.bg)(d),(0,m.Ed)(d,a),(0,m.Aq)(d),(0,m.mv)(d,0,1,{duration:0.3})):rG(a)},onError:function(){rG(a)}})};
var tG=function(){"DELAYED_EMBEDED"in m.sa&&(0,m.z)((0,m.v)("DELAYED_EMBEDED"),function(a){(0,m.Lf)(a.container,a.swf_config)});"MASTHEAD_ENCRYPTED_ID"in m.sa&&(window.masthead=new mF((0,m.v)("MASTHEAD_ENCRYPTED_ID"),(0,m.v)("MASTHEAD_IS_BRANDED")));"PYV_IFRAME_ID"in m.sa&&hG();iG();mG=(0,m.V)(window.document.body,"click",pG,"branded-page-related-channels-item-close");nG.push((0,m.y)("subscription-subscribe-loaded",sG));(0,m.nw)();var a=(0,m.N)("chrome-feed-promo");a&&(a={hl:(0,m.C)(a,"hl")||""},
(0,m.nn)("chrome-feed-promo-show",(0,m.tf)(a)));if(a=(0,m.N)("destination-moments-promo"))a={"impression-count":(0,m.C)(a,"impression-count")||""},(0,m.nn)("destination-moments-promo-show",(0,m.tf)(a))};var uG=function(a){this.j=a;this.ga=(0,m.N)("shared-addto-menu");this.D=(0,m.C)(this.j,"feature")||"";this.Yc=(0,m.C)(this.j,"video-ids")||"";(0,m.Xb)(vG)||(vG=(0,m.yn)(this.ga,"lightweight-panel"));(a=(0,m.P)("sign-in",this.ga))?(0,m.S)(a,"click",(0,m.r)(this.Eo,this)):this.Xc()};
var wG=function(a){var b=[];(0,m.kc)(b,(0,m.O)("playlist-name",a.b.list));(0,m.z)(b,function(a){(0,m.Zf)(a)&&(a=(0,m.Q)(a,"yt-uix-button-menu-item"),a.title=(0,m.C)(a,"possible-tooltip"))})};var xG=function(a,b,c){var d=(0,m.P)("addto-title",a.b.cc);(0,m.zd)(d);(0,m.xd)(d,yG(b,c));zG(a,a.b.cc,!0);b=(0,m.P)("close-note",a.ga);m.R.show(b);var e=(0,m.N)("addto-note");(0,m.S)(e,"keydown",(0,m.r)(a.Bi,a));(0,m.S)(e,"paste",(0,m.r)(a.Bi,a));AG(a.b.cc,function(){e.focus()})};
var yG=function(a,b){var c=window.document.createElement("a");c.href=b;c.innerHTML=a;return c};var AG=function(a,b){if(b){var c=m.od?"webkitTransitionEnd":m.ie?"oTransitionEnd":m.he?"transitionend":m.I&&(0,m.Rc)(10)?"MSTransitionEnd":null;c?(0,m.lg)(a,c,function(){b()}):b()}};
var zG=function(a,b,c){c=c?"slide":"fade";var d=["fade","slide"];(0,m.Hx)(a.k,d);(0,m.W)(a.k,c);(0,m.Hx)(b,d);(0,m.W)(b,c);vG&&b==a.b.list&&(0,m.W)(a.ga,"lightweight-panel");(0,m.yn)(b,"dismissed-panel")?((0,m.Bg)(b,"dismissed-panel"),(0,m.Bg)(a.k,"active-panel")):(c=a.k,(0,m.yn)(c,"active-panel")&&((0,m.Bg)(c,"active-panel"),(0,m.W)(c,"dismissed-panel")));(0,m.W)(b,"active-panel");a.k=b};
var BG=function(a){zG(a,a.b.Qb,!0);CG(a);(0,m.Zb)(a.ga,"video-ids");var b=(0,m.N)("addto-create-playlist");(0,m.S)(b,"keydown",(0,m.r)(a.lg,a));(0,m.S)(b,"paste",(0,m.r)(a.lg,a));AG(a.b.Qb,function(){b.focus()});var c=(0,m.P)("addto-create-cancel-button",a.b.Qb);(0,m.S)(c,"click",(0,m.r)(function(){DG(this)},a));c=(0,m.P)("create-playlist-button",a.b.Qb);(0,m.S)(c,"click",(0,m.r)(a.fo,a))};
var CG=function(a){a.M=(0,m.P)("addto-create-playlist",a.b.Qb);a.P=(0,m.P)("addto-create-playlist-label",a.b.Qb);a.Z=(0,m.P)("create-playlist-button",a.b.Qb);a.G=(0,m.P)("privacy-form",a.b.Qb);(0,m.V)(a.G,"click",(0,m.r)(a.lg,a),"playlist-privacy-option")};var DG=function(a){var b=m.Mn.getInstance(),c=(0,m.Zn)(b,a.ga);c&&(0,m.C)(c,"video-ids")==a.Yc&&(0,m.Pn)(b,c)};
var EG=function(a,b,c,d,e){var g=!(d||"FL"==b||"WL"==b);d={Ma:a.Yc,zh:b,Wf:d,Ah:g?c:null,privacy:e,Yf:a.D,N:(0,m.Cb)(a.gm,c,b),onError:(0,m.Cb)(a.fm,g),W:a};zG(a,a.b.fl);(0,m.Fs)(d);(0,m.Zb)(a.ga,"video-ids");d="";switch(b){case "PL":d=c?"new_pl":"pl";break;case "FL":d="fav";break;case "WL":d="wl"}b={list:d,feature:a.D};(a=(0,m.Yd)(a.j,"a",null))&&a.href&&(a=(0,m.rf)(a.href),b.link_feature=a.feature||"");a=(0,m.tf)(b);(0,m.on)("addto",a,void 0)};
var FG=function(){this.ga=(0,m.N)("tag-editing-menu");this.mm=(0,m.P)("yt-combobox-menu-content",this.ga);this.b=(0,m.P)("yt-combobox-search-input",this.ga);this.j=(0,m.P)("tag-resource-container");this.Ra()};var GG=function(a){a.Ye?a.og=!0:a.Xc()};
var HG=function(a,b){a.k=(0,m.P)("add-new-tag");a.Vi=(0,m.P)("apply-tag-changes");if(b){var c=(0,m.gd)("input","tag-checkbox",void 0);(0,m.z)(c,function(a){var c=b[a.value];(0,m.D)(a,"initial-tag-membership",c);(0,m.D)(a,"current-tag-membership",c);"ALL"==c?a.checked=!0:"SOME"==c&&(0,m.Ao)(a,!0)},a)}IG(a)};
var IG=function(a){for(var b=(0,m.gd)("input","tag-checkbox",void 0),c=!1,d=0;d<b.length;d++)if(!JG(b[d])){c=!0;break}c?(a=a.ga,(0,m.Bg)(a,"show-new"),(0,m.W)(a,"show-apply")):(a=a.ga,(0,m.Bg)(a,"show-apply"),(0,m.W)(a,"show-new"))};var JG=function(a){switch((0,m.C)(a,"initial-tag-membership")){case "SOME":if(a.zf)return!0;break;case "NONE":if(!a.checked)return!0;break;case "ALL":if(a.checked)return!0}return!1};
var KG=function(a,b){if(b){var c=b.error;if(c){var d=(0,m.P)("error-small-template",a.ga),d=(0,m.Wf)(d);LG(a,"yt-alert-error",c,d,8E3)}}};var MG=function(a,b){if(b){var c=b.success_msg;if(c){var d=(0,m.P)("success-small-template",a.ga),d=(0,m.Wf)(d);LG(a,"yt-alert-success",c,d,3E3)}}};var LG=function(a,b,c,d,e){var g=(0,m.P)("tag-menu-notifications",a.ga);(0,m.oq)(b,c,d,g);(0,m.w)((0,m.r)(function(){(new m.tu(d,750)).qa()},a),e)};
var NG=function(a){a=(0,m.gd)("input",a,void 0);for(var b=[],c=[],d=0;d<a.length;d++){var e=a[d];e.zf||(e.checked?b.push(e.value):c.push(e.value))}return{checked_values:b,unchecked_values:c}};var OG=function(){m.Ea.call(this,"www/feed",["www/common"],["feed","index"],PG,QG)};
var PG=function(){m.rp.getInstance().Jb();m.Xw.getInstance().Jb();tG();var a=(0,m.N)("feed");RG.push((0,m.V)(a,"click",QF,"feed-load-more"));RG.push((0,m.V)(a,"click",eG,"feed-item-expander-button"));RG.push((0,m.V)(a,"click",fG,"feed-item-collapser-button"));(0,m.v)("WATCH_FROM_FEED")&&(RG.push((0,m.V)(a,"click",gG,"feed-item-thumb")),RG.push((0,m.V)(a,"click",gG,"feed-video-title")));var b=(0,m.P)("individual-feed"),c=!1;b&&(SG=(0,m.C)(b,"feed-name"),c="user"==(0,m.C)(b,"feed-type"));if("history"==
SG||"watch_later"==SG||"favorites"==SG)CF=b=SG,qF=a,uF=(0,m.N)("feed-item-select-all-checkbox"),GF=(0,m.N)("managed-feed-success"),HF=(0,m.N)("managed-feed-error"),TG=(0,m.P)("branded-page-v2-primary-col-header-container"),xF=(0,m.P)("addto-button",TG),yF=(0,m.N)("feed-item-remove-videos"),zF=(0,m.N)("tag-menu-button"),AF=(0,m.N)("managed-toolbar-play-all-button"),FF=(0,m.N)("feed-title-count"),UG.push((0,m.S)(uF,"click",rF)),UG.push((0,m.V)(window.document.body,"click",tF,"feed-item-selection-action")),
UG.push((0,m.V)(window.document.body,"click",wF,"feed-item-checkbox")),UG.push((0,m.S)(yF,"click",BF)),"history"==b&&(UG.push((0,m.S)((0,m.N)("watch-history-pause-button"),"click",IF)),UG.push((0,m.S)((0,m.N)("watch-history-resume-button"),"click",LF)),UG.push((0,m.V)(window.document.body,"click",OF,"watch-history-clear-button")));(0,m.$v)({"feed-load-more":RF});if((0,m.v)("INIT_AUTOSHARE")){b=new oF((0,m.G)("autoshare"));b.addServiceChangedCallback(VF);var d=(0,m.N)("facebook-connect-button");d&&
b.registerConnectDialogLauncher(d,"facebook",!0);(d=(0,m.N)("twitter-connect-button"))&&b.registerConnectDialogLauncher(d,"twitter",!0);(d=(0,m.N)("orkut-connect-button"))&&b.registerConnectDialogLauncher(d,"orkut",!0);window.autoshare=b}"music-promo-1"==(0,m.v)("MUSIC_PROMO_TYPE")?(b=(0,m.N)("music-engagement-promo"),RG.push((0,m.V)(b,"click",WF,"mep-dismiss-button")),RG.push((0,m.V)(b,"click",YF,"mep-dismiss-artist-button")),RG.push((0,m.V)(b,"click",$F,"mep-artist-thumb")),ZF=(0,m.C)((0,m.N)("mep-container"),
"ids-for-replacement").split(",")):"music-promo-2"==(0,m.v)("MUSIC_PROMO_TYPE")&&(b=(0,m.N)("mep-container"),VG.push((0,m.y)("subscription-subscribe-success",aG)),RG.push((0,m.V)(b,"click",cG,"mep2-dismiss-button")),RG.push((0,m.V)(b,"click",dG,"channel-lockup")),ZF=(0,m.C)(b,"ids-for-replacement").split(","));(0,m.ow)(a,c);(0,m.Av)(0);(0,m.Bv)()};
var QG=function(){(0,m.qa)("DELAYED_EMBEDED",[]);window.masthead&&window.masthead.dispose();jG&&((0,m.U)(jG),jG=null);lG();(0,m.jq)(m.mw);UF=null;(0,m.U)(RG);(0,m.Da)(VG);if("history"==SG||"watch_later"==SG||"favorites"==SG)(0,m.U)(UG),UG=[],zF=GF=HF=uF=FF=AF=yF=xF=TG=qF=null};var SG,UF;(0,m.t)(mF,m.oa);m.f=mF.prototype;m.f.O=function(){mF.L.O.call(this);(0,m.U)(this.b);this.b=null};
m.f.ar=function(){m.R.hide("ad_creative_1");(0,m.A)("ads-masthead-hide");(0,m.Cq)((0,m.N)("page"),!0);this.D&&m.R.hide("ad_creative_collapse_btn_1");m.R.show("ad_creative_expand_btn_1");(0,m.K)(this.k,"masthead-ad-expanded");nF(this.j);(0,m.on)("homepage_collapse_masthead_ad",void 0,void 0)};m.f.xh=function(){m.R.show("ad_creative_expand_btn_1");(0,m.Dd)((0,m.N)("premium-yva"));(0,m.Dd)((0,m.N)("video-masthead"));nF(this.j)};
m.f.Xq=function(){(0,m.$c)(window.document.getElementById("premium-yva"),"premium-yva-unexpanded","premium-yva-expanded")};m.f.Yq=function(){(0,m.$c)(window.document.getElementById("premium-yva"),"premium-yva-expanded","premium-yva-unexpanded")};m.f.Qq=function(){m.R.hide("premium-yva");(0,m.K)((0,m.N)("premium-yva"),"premium-yva-unexpanded")};m.f.br=function(){var a=m.Re.getInstance();a.set("HIDDEN_MASTHEAD_ID",!1);a.save();(0,m.on)("homepage_expand_masthead_ad",void 0,void 0);(0,m.Tp)(window.document.location.href)};(0,m.s)("yt.sharing.AutoShare",oF);oF.prototype.Qa=function(a,b,c,d){(0,m.S)(a,"click",(0,m.r)(this.P,this));if(a.id)this.J[a.id]={serviceName:b,connectOnly:c},d&&(this.J[a.id].connectOnlyCallback=d);else throw"Connect dialog launch buttons must have an id.";};oF.prototype.registerConnectDialogLauncher=oF.prototype.Qa;oF.prototype.P=function(a){if(a=this.J[a.currentTarget.id]){var b=a.connectOnly;a.connectOnlyCallback&&(b=(0,a.connectOnlyCallback)());this.G(a.serviceName,b)}};
oF.prototype.handleConnectService=oF.prototype.P;oF.prototype.oa=function(){this.j()};oF.prototype.doOnLoad=oF.prototype.oa;oF.prototype.ha=function(a){this.H.push(a)};oF.prototype.addServiceChangedCallback=oF.prototype.ha;oF.prototype.aa=function(a){this.F.push(a)};oF.prototype.addCanConnectCallback=oF.prototype.aa;oF.prototype.xa=function(){return this.k};oF.prototype.getServiceInfo=oF.prototype.xa;
oF.prototype.G=function(a,b){for(var c in this.F)if(!(0,this.F[c])(this,a,b))return;(0,m.X)(this.b+"autoshare",{Q:{action_ajax_stats_ping:"1",stat:"connect_has_google",service:a}});c=this.b+"autoshare?action_popup_auth=1&service="+a+"&connect_only="+(b?"True":"False")+"&root_url="+(0,window.encodeURIComponent)(this.b);"facebook"==a&&(c+="&permissions="+(0,window.encodeURIComponent)("read_stream,offline_access,manage_pages,user_likes,publish_stream"));this.$(c,{height:500,width:860})};
oF.prototype.connectService=oF.prototype.G;oF.prototype.pa=function(a,b){var c=(0,m.r)(function(a,c){this.k=(0,m.xh)(c.html_content);this.j();b&&b()},this),d=(0,m.r)(function(){b&&b();this.j()},this),e={action_ajax_connect_service:1};e.return_url=a;(0,m.X)(this.b+"autoshare?ajax_connect_service",{format:"XML",method:"POST",yb:(0,m.tf)(e)+"&"+this.M,N:c,onError:d})};oF.prototype.connectServiceDone=oF.prototype.pa;oF.prototype.la=function(a){this.Z(a)};oF.prototype.disconnectService=oF.prototype.la;
oF.prototype.Zb=function(a,b){var c=(0,m.r)(function(a,b){this.k=(0,m.xh)(b.html_content);this.j()},this),d=(0,m.r)(function(){this.j()},this),e={action_ajax_set_connect_only:1};e.service=a;e.connect_only=b?"True":"False";(0,m.X)(this.b+"autoshare?ajax_set_connect_only",{format:"XML",method:"POST",yb:(0,m.tf)(e)+"&"+this.M,N:c,onError:d})};oF.prototype.setConnectOnly=oF.prototype.Zb;
oF.prototype.Z=function(a){var b=(0,m.r)(function(a,b){this.k=(0,m.xh)(b.html_content);this.j()},this),c=(0,m.r)(function(){this.j()},this),d={action_ajax_disconnect_service:1};d.service=a;(0,m.X)(this.b+"autoshare?ajax_disconnect_service",{format:"XML",method:"POST",yb:(0,m.tf)(d)+"&"+this.M,N:b,onError:c})};oF.prototype.j=function(){for(var a in this.H)(0,this.H[a])(this)};oF.prototype.$=function(a,b){if(this.D)try{this.D.close()}catch(c){this.D=null}this.D=!(0,m.Wp)(a,b)};
oF.prototype.Cf=function(){this.G("facebook",!this.k.facebook.is_autosharing)};var CF,qF,TG,xF,yF,AF,FF,uF,HF,GF,zF,UG=[];var RG=[],VG=[],ZF=[];var jG;var mG,nG=[],oG=[];var WG,XG,vG;m.f=uG.prototype;
m.f.Xc=function(){var a=(0,m.C)(this.j,"hide-watch-later"),b={action_get_dropdown:"1",hide_favorites:(0,m.C)(this.j,"hide-favorites"),hide_watch_later:a,video_ids:this.Yc};this.D&&(b.feature=this.D);(0,m.X)("/addto_ajax",{Pf:!0,format:"XML",method:"GET",W:this,Q:b,N:function(b,d){this.ga.innerHTML=d.html_content||"";(0,m.Ag)(this.ga,"no-watch-later",!!a);(0,m.Ag)(this.ga,"ie",m.I);var e=(0,m.O)("contains-selected-videos",this.ga),g=[];e&&(0,m.z)(e,function(a){g.push({id:(0,m.C)(a,"item-id"),name:(0,m.C)(a,
"item-name")})});(0,m.A)("addto-menu-loaded",{videoIds:this.Yc,selectedPlaylists:g});this.Ra();wG(this)}})};
m.f.Ra=function(){this.b={};this.b.list=(0,m.N)("addto-list-panel");this.b.fl=(0,m.N)("addto-list-saving-panel");this.b.Lf=(0,m.N)("addto-list-saved-panel");this.b.Te=(0,m.N)("addto-list-error-panel");this.b.cc=(0,m.N)("addto-note-input-panel");this.b.Kh=(0,m.N)("addto-note-saving-panel");this.b.ai=(0,m.N)("addto-note-saved-panel");this.b.jg=(0,m.N)("addto-note-error-panel");this.b.Qb=(0,m.N)("addto-create-panel");this.k=this.b.list;(0,m.V)(this.b.list,"click",(0,m.r)(this.cn,this),"yt-uix-button-menu-item");
this.F=(0,m.P)("playlist-save-note",this.b.cc);(0,m.S)(this.F,"click",(0,m.r)(this.dn,this));var a=(0,m.P)("close-button",this.ga);(0,m.S)(a,"click",(0,m.r)(this.bn,this))};m.f.cn=function(a){a.stopPropagation();var b=a.currentTarget;(0,m.Fp)(m.zp.getInstance(),b);a=(0,m.C)(b,"list-action");var c=(0,m.C)(b,"item-id")||"",b=(0,m.C)(b,"item-name")||"",d;switch(a){case "create-playlist":BG(this);return;case "favorites":d="FL";break;case "watch-later":d="WL";break;case "playlist":d="PL"}EG(this,d,b,c)};
m.f.Bi=function(a){var b=a.target,c=(0,m.P)("addto-note-label",this.b.cc);(0,m.w)((0,m.r)(function(){var a=(0,m.Sb)(b.value);a?m.R.show(c):m.R.hide(c);!a&&this.J&&this.H?(0,m.Yf)(this.F,!0):(0,m.Yf)(this.F,!1)},this),0)};m.f.fo=function(){var a=this.M.value,b=(0,m.Xl)(this.G,"privacy");EG(this,"PL",a,null,b)};
m.f.lg=function(){(0,m.w)((0,m.r)(function(){var a=(0,m.Sb)(this.M.value);a?m.R.show(this.P):m.R.hide(this.P);var b=(0,m.Xl)(this.G,"privacy");a||!b?(0,m.Yf)(this.Z,!1):(0,m.Yf)(this.Z,!0)},this),0)};m.f.bn=function(){DG(this)};
m.f.gm=function(a,b,c,d){this.J=d.list_id||"";this.H=d.setvideo_id||"";c=d.list_url||"";d="True"==d.show_private_video_warning;this.J&&this.H&&((0,m.Sb)((0,m.N)("addto-note").value)||(0,m.Yf)(this.F,!0),d&&(d=(0,m.O)("private-video-warning",this.ga))&&m.R.show.apply(m.R,d),d=this.Yc.split(","),b="FL"==b,(0,m.C)(this.j,"reload-menu-after-save")?this.Xc():b||1<d.length?(b=(0,m.P)("addto-title",this.b.Lf),(0,m.zd)(b),a=yG(a,c),b.appendChild(a),(0,m.Bg)(this.ga,"lightweight-panel"),zG(this,this.b.Lf,
!0),a=(0,m.P)("close-note",this.ga),m.R.show(a)):xG(this,a,c))};
m.f.fm=function(a,b,c){if(b=c&&c.error_message){(0,m.P)("error-details",this.b.Te).innerHTML=b;b=(0,m.P)("show-menu-link",this.b.Te);var d=(0,m.S)(b,"click",(0,m.r)(function(b){b.preventDefault();(0,m.U)(d);(0,m.Hx)(this.b.cc,["dismissed-panel","fade","slide"]);(0,m.Hx)(this.b.Lf,["dismissed-panel","fade","slide"]);b=(0,m.P)("close-note",this.ga);m.R.hide(b);a?zG(this,this.b.Qb,!0):zG(this,this.b.list,!0)},this));if(b=(0,m.N)("addto-create-name"))b.disabled=!1;(0,m.Hx)(this.b.Te,["dismissed-panel",
"fade","slide"]);zG(this,this.b.Te)}else DG(this)};m.f.dn=function(){(0,m.X)("/playlist_bar_ajax",{method:"POST",Pf:!0,Q:{action_set_playlist_item_annotation:1},R:{annotation:(0,m.N)("addto-note").value,playlist_id:this.J,setvideo_id:this.H,session_token:(0,m.G)("playlist_bar_ajax")},N:this.sn,onError:this.rn,W:this});zG(this,this.b.Kh)};
m.f.sn=function(){var a=(0,m.P)("addto-title",this.b.cc),b=(0,m.Vf)(a);(0,m.W)(b,"yt-uix-tooltip-reverse");(0,m.P)("panel-content",this.b.ai).appendChild(b);zG(this,this.b.ai);(0,m.w)((0,m.r)(function(){(0,m.Fp)(m.zp.getInstance(),b);DG(this)},this),3E3)};
m.f.rn=function(a,b){var c=b&&b.errors;if(c){var d=(0,m.P)("error-details",this.b.jg);(0,m.zd)(d);(0,m.z)(c,function(a){var b=window.document.createElement("li");b.innerHTML=a;d.appendChild(b)});var c=(0,m.P)("add-note-link",this.b.jg),e=(0,m.S)(c,"click",(0,m.r)(function(a){a.preventDefault();(0,m.U)(e);(0,m.Bg)(this.b.Kh,"dismissed-panel");zG(this,this.b.cc)},this));zG(this,this.b.jg)}else DG(this)};
m.f.Eo=function(){var a=(0,m.vf)("/addto_ajax",{action_redirect_to_signin_with_add:1,list_type:"WL",video_ids:this.Yc,next_url:window.document.location}),b=(0,m.vd)("form");b.action=a;b.method="POST";a=(0,m.vd)("input");a.type="hidden";a.name="session_token";a.value=(0,m.G)("addto_ajax_logged_out");b.appendChild(a);window.document.body.appendChild(b);b.submit()};(0,m.Jc)(FG);m.f=FG.prototype;m.f.Ye=!1;m.f.og=!1;
m.f.Xc=function(){var a={},b=this.b.value;(0,m.Sb)(b)||(a.search=b);var b=[],c=[],b=NG("tag-video-checkbox").checked_values,c=NG("tag-playlist-checkbox").checked_values;this.Ye=!0;this.og=!1;(0,m.X)("/labels_ajax?action_tag_menu_dropdown=1",{method:"POST",W:this,Q:a,R:{video_ids:b,playlist_ids:c},N:function(a,b){var c=b.tag_membership;this.mm.innerHTML=b.html_content||"";HG(this,c);this.Ye=!1;(0,m.Bg)(this.ga,"loading");(0,m.xo)();this.og&&this.Xc()},onError:function(a){this.Ye=!1;(0,m.Bg)(this.ga,
"loading");KG(this,(0,m.wh)(a.response))}})};
m.f.Ra=function(){(0,m.S)(this.b,"keydown",(0,m.r)(this.Yh,this));(0,m.S)(this.b,"paste",(0,m.r)(this.Yh,this));(0,m.V)(this.ga,"click",(0,m.r)(this.Um,this),"tag-checkbox");(0,m.V)(this.ga,"click",(0,m.r)(this.Tm,this),"add-new-tag");(0,m.V)(this.ga,"click",(0,m.r)(this.Sm,this),"apply-tag-changes");this.j&&((0,m.V)(this.j,"click",(0,m.r)(this.ig,this),"tag-video-checkbox"),(0,m.V)(this.j,"click",(0,m.r)(this.ig,this),"tag-playlist-checkbox"));(0,m.V)(window.document.body,"click",(0,m.r)(this.ig,
this),"tag-refresh")};m.f.Yh=function(){(0,m.w)((0,m.r)(function(){GG(this)},this),0)};m.f.Um=function(a){a=a.target;switch((0,m.C)(a,"current-tag-membership")){case "SOME":a.zf=!1;(0,m.D)(a,"current-tag-membership","NONE");break;case "NONE":(0,m.D)(a,"current-tag-membership","ALL");break;case "ALL":"SOME"==(0,m.C)(a,"initial-tag-membership")?((0,m.Ao)(a,!0),(0,m.D)(a,"current-tag-membership","SOME")):(0,m.D)(a,"current-tag-membership","NONE")}IG(this)};m.f.ig=function(){(0,m.W)(this.ga,"loading")};
m.f.Tm=function(){this.k.disabled=!0;var a=this.b.value,b=NG("tag-video-checkbox").checked_values,c=NG("tag-playlist-checkbox").checked_values,a={title:a,video_ids:b,playlist_ids:c},a={method:"POST",Q:{session_token:(0,m.C)(this.ga,"ajax-token")},R:a,N:function(a,b){MG(this,b);GG(this)},onError:function(a){KG(this,(0,m.wh)(a.response));GG(this)},W:this};(0,m.X)("/labels_ajax?action_create_and_apply_tag=1",a)};
m.f.Sm=function(){this.Vi.disabled=!0;var a=NG("tag-video-checkbox").checked_values,b=NG("tag-playlist-checkbox").checked_values,c=NG("tag-checkbox"),d=(0,m.gd)("input","tag-checkbox",void 0).length;(0,m.X)("/labels_ajax?action_update_membership=1",{W:this,method:"POST",Q:{session_token:(0,m.C)(this.ga,"ajax-token")},R:{video_ids:a,playlist_ids:b,tags_to_add:c.checked_values,tags_to_remove:c.unchecked_values,num_tags:d},N:function(a,b){MG(this,b);GG(this)},onError:function(a){this.Vi.disabled=!1;
KG(this,(0,m.wh)(a.response))}})};(0,m.s)("yt.flash.embed",m.Lf);(0,m.s)("yt.www.ads.pyv.pyvHomeAfcCallback",m.Yv);(0,m.s)("yt.www.ads.MastheadAd",mF);
(0,m.s)("yt.www.lists.addto.toggleMenu",function(a,b){var c=m.zp.getInstance(),d=(0,m.Y)(c),e=(0,m.N)("shared-addto-menu");if(b){var g=(0,m.P)("addto-menu",e);(0,m.Fp)(c,a);XG=(0,m.Bg)(a,d);WG||(WG=g.innerHTML);c=(0,m.C)(e,"video-ids");d=(0,m.C)(a,"video-ids");vG&&(0,m.W)(e,"lightweight-panel");(0,m.yn)(a,"flip")&&(0,m.W)(e,"flip");d&&c!=d&&((0,m.D)(e,"video-ids",d),g.innerHTML=WG,new uG(a))}else XG&&(0,m.W)(a,d),(0,m.Bg)(e,"flip")});
(0,m.s)("yt.www.TagEditingMenu.toggleTagMenu",function(a,b){if(b){var c=(0,m.N)("tag-editing-menu");(0,m.yn)(c,"loading")?FG.getInstance().Xc():(FG.getInstance(),(0,m.xo)());c=(0,m.P)("yt-combobox-search-input",c);(0,m.w)((0,m.r)(c.focus,c),0)}});mF.prototype.autoCollapsePremiumYva=mF.prototype.Qq;mF.prototype.collapse_ad=mF.prototype.ar;mF.prototype.expand_ad=mF.prototype.br;mF.prototype.userCollapsePremiumYva=mF.prototype.xh;mF.prototype.userExpandPremiumYva=mF.prototype.Xq;
mF.prototype.userUnexpandPremiumYva=mF.prototype.Yq;(0,m.t)(OG,m.Ea);OG.prototype.enable=function(){OG.L.enable.call(this);(0,m.Gn)(m.ep);(0,m.Gn)(m.Xw)};OG.prototype.disable=function(){OG.L.disable.call(this);(0,m.In)(m.ep);(0,m.In)(m.Xw)};(0,m.Fa)(new OG);})(_yt_www);
